# https://taskfile.dev

version: '3'

includes:
  macos:
    taskfile: macos
    internal: true
    vars:
      LITELLM_PORT:
        ref: .LITELLM_PORT
      LITELLM_PROXY_URL:
        ref: .LITELLM_PROXY_URL

vars:
  LITELLM_PORT: '4444'
  LITELLM_PROXY_URL: 'http://127.0.0.1:{{.LITELLM_PORT}}/v1'
  HOME:
    sh: cd ~ && pwd

env:
  LITELLM_PROXY_URL: '{{.LITELLM_PROXY_URL}}'

tasks:
  debug:
    cmds:
      - task: macos:debug
        platforms: [darwin]

  litellm:
    desc: Installs and starts LiteLLM authenticating proxy
    aliases:
      - default
    cmds:
      - task: litellm:configure
      - task: litellm:start

  litellm:start:
    desc: Starts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: macos:service:start
        platforms: [darwin]

  litellm:stop:
    desc: Stops LiteLLM authenticating proxy
    run: once
    cmds:
      - task: macos:service:stop
        platforms: [darwin]

  litellm:restart:
    desc: Restarts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: macos:service:restart
        platforms: [darwin]

  litellm:configure:
    desc: Configures LiteLLM authenticating proxy
    run: once
    cmds:
      - cmd: mkdir -p ~/.config/litellm/providers
        silent: true
      - cmd: cp -r ./litellm/providers/*.yaml ~/.config/litellm/providers/
      - cmd: sed -e 's/HOME/{{.HOME}}/g' ./litellm/config.yaml > ~/.config/litellm/config.yaml
    status:
      - test -e ~/.config/litellm/providers
      - test -e ~/.config/litellm/config.yaml

  opencode:configure:
    desc: Configures OpenCode to include LiteLLM proxy info
    run: once
    cmds:
      - cmd: python3 ./opencode/configure.py
