# https://taskfile.dev

version: '3'

includes:
  docker:
    taskfile: docker
    internal: true

vars:
  LITELLM_PORT: '4444'
  LITELLM_PROXY_URL: 'http://127.0.0.1:{{.LITELLM_PORT}}/v1'
  HOME:
    sh: cd ~ && pwd

env:
  LITELLM_PROXY_URL: '{{.LITELLM_PROXY_URL}}'

tasks:
  litellm:
    desc: Installs and starts LiteLLM authenticating proxy
    aliases:
      - default
    cmds:
      - task: litellm:configure
      - task: litellm:start

  litellm:start:
    desc: Starts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: litellm:env
      - task: docker:service:start
        silent: true

  litellm:stop:
    desc: Stops LiteLLM authenticating proxy
    run: once
    cmds:
      - task: docker:service:stop
        silent: true

  litellm:restart:
    desc: Restarts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: docker:service:restart
        silent: true

  litellm:logs:
    desc: View logs for LiteLLM authenticating proxy
    run: once
    interactive: true
    silent: true
    cmds:
      - task: docker:logs
  
  litellm:env:
    desc: Refreshes LiteLLM credentials
    run: once
    silent: true
    cmds:
      - cmd: mkdir -p '{{.HOME}}/.local/state/litellm'
      - cmd: |
          {
            # TODO: More environment variables
            env | awk '/BOBSHELL/ { print("export", $0) }'
          } > '{{.HOME}}/.local/state/litellm/env'

  litellm:configure:
    desc: Configures LiteLLM authenticating proxy
    run: once
    cmds:
      - cmd: mkdir -p '{{.HOME}}/.config/litellm/providers'
        silent: true
      - cmd: cp -r ./litellm/providers/*.yaml '{{.HOME}}/.config/litellm/providers/'
      - cmd: sed -e 's/HOME/{{.HOME}}/g' ./litellm/config.yaml > '{{.HOME}}/.config/litellm/config.yaml'
      - task: litellm:env
    status:
      - test -e '{{.HOME}}/.config/litellm/providers'
      - test -e '{{.HOME}}/.config/litellm/config.yaml'

  opencode:configure:
    desc: Configures OpenCode to include LiteLLM proxy info
    run: once
    cmds:
      - cmd: python3 ./opencode/configure.py
