# https://taskfile.dev

version: '3'

includes:
  docker:
    taskfile: docker
    internal: true

vars:
  LITELLM_PORT: '4444'
  LITELLM_PROXY_URL: 'http://127.0.0.1:{{.LITELLM_PORT}}'
  HOME:
    sh: cd ~ && pwd

env:
  LITELLM_PROXY_URL: '{{.LITELLM_PROXY_URL}}'

tasks:
  litellm:
    desc: Installs and starts LiteLLM authenticating proxy
    aliases:
      - default
    cmds:
      - task: litellm:configure
      - task: litellm:start

  litellm:start:
    desc: Starts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: litellm:env
      - task: litellm:providers
      - task: docker:service:start
        silent: true

  litellm:stop:
    desc: Stops LiteLLM authenticating proxy
    run: once
    cmds:
      - task: docker:service:stop
        silent: true

  litellm:restart:
    desc: Restarts LiteLLM authenticating proxy
    run: once
    cmds:
      - task: docker:service:restart
        silent: true

  litellm:logs:
    desc: View logs for LiteLLM authenticating proxy
    run: once
    interactive: true
    silent: true
    cmds:
      - task: docker:logs
  
  litellm:env:
    desc: Refreshes LiteLLM credentials
    run: once
    silent: true
    cmds:
      - cmd: mkdir -p '{{.HOME}}/.local/state/litellm'
      - cmd: |
          {
            # TODO: More environment variables
            env | awk '/BOBSHELL/ { print("export", $0) }'
          } > '{{.HOME}}/.local/state/litellm/env'

  litellm:configure:
    desc: Configures LiteLLM authenticating proxy
    run: once
    cmds:
      - cmd: cp ./litellm/config.yaml '{{.HOME}}/.config/litellm/config.yaml'
      - task: litellm:providers
      - task: litellm:env
    status:
      - test -e '{{.HOME}}/.config/litellm/config.yaml'

  litellm:providers:
    desc: Sync available models from backend LLM providers
    run: once
    silent: true
    deps:
      - uv:install
    cmds:
      - cmd: |
          mkdir -p \
            './litellm/providers' \
            '{{.HOME}}/.config/litellm/providers' \
            '{{.HOME}}/.local/state/litellm/github_copilot'
        silent: true
      - cmd: ./scripts/generate-ibm-bob.py
      - cmd: ./scripts/generate-copilot.py
      - cmd: cp ./litellm/providers/*.yaml '{{.HOME}}/.config/litellm/providers/'

  uv:install:
    desc: Install `uv` runtime for Python
    run: once
    interactive: true
    internal: true
    silent: true
    cmds:
      - cmd: brew install uv
        platforms: [darwin]
      - cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
        platforms: [linux]
    status:
      - command -v uv

  opencode:configure:
    desc: Configures OpenCode to include LiteLLM proxy info
    run: once
    cmds:
      - cmd: ./scripts/configure-opencode.py
