---
include:
  - providers/ibm_bob.yaml
  - providers/github_copilot.yaml

model_list: []
  # - model_name: ''
  #   litellm_params:
  #     model: ''
  #     api_key: ''
  #     reasoning_effort: 'high'
  #     max_tokens: 9000
  #     thinking:
  #       type: 'enabled'
  #       budget_tokens: 4000 # Must not be higher than `max_tokens`
